### ISSUE TITLE
[academics-faculties.html] - Background glitch with commit `dbf7a7e`

### ISSUE THREAD

**Issue by ItsSitanshu** [TriyogHS/triyoghs.github.io#4]
Expected:
The background should be an image
Current Sitiation:
![IMG](https://i.imgur.com/BDGbr5s.png)

**Comment by ItsSitanshu** [comment]
Please use the [dbf7a7e](https://github.com/TriyogHS/triyoghs.github.io/tree/dbf7a7e-mobile) for future commits.

**Comment by ItsSitanshu** [comment]
Commit dbf7a7e broke the mobile  website

**Comment by ItsSitanshu** [comment]
**MISCOMMUNICATION IN THE TEAM**
Apologies,
Sitanshu

**Comment by suvashish26** [comment]
Fixed
