### ISSUE TITLE
Js Path incorrect

### ISSUE THREAD

**Issue by suvashish26** [TriyogHS/triyoghs.github.io#6]
**CODE**
```
<script type="text/javascript" src="static/js/app.js"></script>
    <script type="text/javascript" src="static/js/particles.js"></script>
```
It was working until the js folder and particles.js folder were outside the static but an issue occurred when kept inside the static folder. Supposed to be an animation in the bg but its not present ( Used particles.js)
![image](https://user-images.githubusercontent.com/77734238/145700601-88a3721d-0773-4ce4-8c7c-6fc5d82e0961.png)
Meant to be like this
![image](https://user-images.githubusercontent.com/77734238/145700732-94504b25-a924-4ba2-a2de-000ead0704e6.png)

**Comment by ItsSitanshu** [comment]
Going to code it  up soon should be done by 5 pm -
Please do mention some possible issues @suvashish26

**Comment by TheCoolGDev** [comment]
Fixed it in PR. #7
